In [3]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([2.000,416.500,270.720 ]) # 240913 X:2.000 Y:416.500 Z:270.720 
pl=np.array([461.500,415.000,280.720]) # 240913 X:461.500 Y:415.000 Z:280.720
pt=np.array([235.000,416.500,505.720]) # X:235.000 Y:416.500 Z:505.720

pcxz=(pr+pl)/2

print(pcxz)

hi
[231.75 415.75 275.72]


In [4]:
pz = pt - pcxz
print(pz)
px = pr-pl
print(px)
py = np.cross(px,pz)
py
p_x = pr-pcxz
print(p_x)
p_z = pt-pcxz
print(p_z)
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*(240+9) + p_y*probe_distance_from_tip

print(centerpoint)

[  3.25   0.75 230.  ]
[-459.5    1.5  -10. ]
[-229.75    0.75   -5.  ]
[  3.25   0.75 230.  ]
[-0.00114739 -0.99998169  0.00594097]
[231.46194728 164.70459572 277.21148095]


In [8]:
step = 10
radius = 95
npts = 4/3*np.pi*(radius/step)**3
t = npts #s
print(t)
print(t/60)
print(t/60/60)


3591.3640018287315
59.85606669714552
0.997601111619092


In [14]:
radius = 85
resol = 10
nperrad = int(radius/resol)+1
print(nperrad)
print(radius/nperrad)

9
9.444444444444445
