In [1]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([11.000,413.000,270.130]) # 240906 X:11.000 Y:413.000 Z:270.130
pl=np.array([469.000,417.000,282.130]) # 240906 X:469.000 Y:417.000 Z:282.130
pt=np.array([242.000,425.000,506.130]) # 240906 X:242.000 Y:425.000 Z:506.130

pcxz=(pr+pl)/2

print(pcxz)

hi


[240.   425.5  276.13]


In [4]:
pz = pt - pcxz
print(pz)
px = pr-pl
print(px)
py = np.cross(px,pz)
py
p_x = pr-pcxz
print(p_x)
p_z = pt-pcxz
print(p_z)
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*(240+9) + p_y*probe_distance_from_tip

print(centerpoint)

[  2.   -0.5 230. ]
[-458.   -5.  -12.]
[-229.    -2.5   -6. ]
[  2.   -0.5 230. ]
[ 1.33079382e-02 -9.99911383e-01  3.53956837e-04]
[243.34095788 174.47224734 276.21886086]


In [ ]:
2.5*1753/60/60

In [ ]:
(0.41-0.56)/47.5*1e6