In [2]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([5.000,455.000,297.000]) # 240826
pl=np.array([465.000,446.000,307.000]) # 240826
pt=np.array([238.00,450.000,533.000]) # X:238.000 Y:439.000 Z:530.000

pcxz=(pr+pl)/2

print(pcxz)

hi
[235.  450.5 302. ]


In [5]:
pz = pt - pcxz
print(pz)
px = pr-pl
print(px)
py = np.cross(px,pz)
py
p_x = pr-pcxz
print(p_x)
p_z = pt-pcxz
print(p_z)
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*(240+9) + p_y*probe_distance_from_tip
2.05
print(centerpoint)

[  3.   -0.5 231. ]
[-460.    9.  -10.]
[-230.     4.5   -5. ]
[  3.   -0.5 231. ]
[-1.73825868e-02 -9.99848474e-01  9.35767317e-04]
[230.63610158 199.48804072 302.23492438]


In [6]:
2.5*1753/60/60

1.2173611111111111

In [12]:
(0.41-0.56)/47.5*1e6

-3157.894736842107