In [3]:
print("hi")
import numpy as np
# magnet facing cosi
pr=np.array([5,436,308]) # X:33 Y:432 Z:307
pl=np.array([490,428,300]) # X:495.000 Y:355.000 Z:181.000
pt=np.array([248,438,544]) # X:254.000 Y:367.000 Z:420.000

pcxz=(pr+pl)/2

print(pcxz)

hi
[247.5 432.  304. ]


In [4]:
pz = pt - pcxz
print(pz)

[  0.5   6.  240. ]


In [5]:
px = pr-pl
print(px)

[-485    8    8]


In [6]:
py = np.cross(px,pz)

In [7]:
py

array([  1872., 116404.,  -2914.])

In [8]:
p_x = pr-pcxz
print(p_x)

[-242.5    4.     4. ]


In [9]:
p_z = pt-pcxz
print(p_z)

[  0.5   6.  240. ]


In [10]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[-0.01400093 -0.99951726  0.02773468]


In [11]:
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*220 + p_y*probe_distance_from_tip

print(centerpoint)

[244.39109361 210.05719149 310.15848617]


In [23]:
fname = r'C:\cosi-measure\Software\COSI2\data\240708\Hamburg_ball_R130mm_d10mm.path'
file = open(fname)
lines = file.readlines()
xs  = []
ys  = []
zs  = []

for line in lines:
    xstr = line.split(' ')[0]
    ystr = line.split(' ')[1]
    zstr = line.split(' ')[2]
    x = float(xstr[1:])
    y = float(ystr[1:])
    z = float(zstr[1:])
    xs.append(x)
    ys.append(y)
    zs.append(z)
    
print('min x',min(xs))
print('max x',max(xs))
print('min y',min(ys))
print('max y',max(ys))
print('min z',min(zs))
print('max z',max(zs))

min x 124.0
max x 364.0
