In [1]:
print("hi")
import numpy as np
# magnet facing cosi
pr=np.array([9,370,168]) # X:9.000 Y:370.000 Z:168.000
pl=np.array([495,355,181]) # X:495.000 Y:355.000 Z:181.000
pt=np.array([254,367,420]) # X:254.000 Y:367.000 Z:420.000

pcxz=(pr+pl)/2

print(pcxz)

hi
[252.  362.5 174.5]


In [2]:
pz = pt - pcxz
print(pz)

[  2.    4.5 245.5]


In [3]:
px = pr-pl
print(px)

[-486   15  -13]


In [4]:
py = np.cross(px,pz)

In [5]:
py

array([  3741., 119287.,  -2217.])

In [6]:
p_x = pr-pcxz
print(p_x)

[-243.     7.5   -6.5]


In [7]:
p_z = pt-pcxz
print(p_z)

[  2.    4.5 245.5]


In [8]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[-0.0293194  -0.99936805  0.02009669]


In [9]:
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*220 + p_y*probe_distance_from_tip

print(centerpoint)

[245.48962698 140.59032489 178.96246979]
