In [1]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([4.000,413.000,198.500]) # X:4.000 Y:413.000 Z:198.500
pl=np.array([463.000,410.000,209.500]) # X:463.000 Y:410.000 Z:209.500
pt=np.array([238.000,410.000,434.500]) # X:238.000 Y:410.000 Z:434.500

pcxz=(pr+pl)/2

print(pcxz)

hi
[233.5 411.5 204. ]


In [2]:
pz = pt - pcxz
print(pz)

[  4.5  -1.5 230.5]


In [3]:
px = pr-pl
print(px)

[-459.    3.  -11.]


In [4]:
py = np.cross(px,pz)

In [5]:
py

array([   675., 105750.,    675.])

In [6]:
p_x = pr-pcxz
print(p_x)

[-229.5    1.5   -5.5]


In [7]:
p_z = pt-pcxz
print(p_z)

[  4.5  -1.5 230.5]


In [8]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[-0.00419117 -0.99998122 -0.00447122]


In [9]:
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*(240+9) + p_y*probe_distance_from_tip
2.05
print(centerpoint)

[232.44780642 160.45471447 202.8775013 ]
