In [12]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([]) # 37.000 Y:453.000 Z:264.500
pl=np.array([]) # X:497.000 Y:454.000 Z:274.500
pt=np.array([]) # X:270.000 Y:455.000 Z:499.500

pcxz=(pr+pl)/2

print(pcxz)

hi
[267.  453.5 269.5]


In [13]:
pz = pt - pcxz
print(pz)

[  3.    1.5 228. ]


In [14]:
px = pr-pl
print(px)

[-460.   -1.  -10.]


In [15]:
py = np.cross(px,pz)

In [16]:
py

array([  -213., 104850.,   -687.])

In [17]:
p_x = pr-pcxz
print(p_x)

[-230.    -0.5   -5. ]


In [18]:
p_z = pt-pcxz
print(p_z)

[  3.    1.5 228. ]


In [19]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[ 0.00459761 -0.99994746  0.0091617 ]


In [21]:
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*(240+9) + p_y*probe_distance_from_tip
2.05
print(centerpoint)

[268.15423093 202.46318987 271.80004558]
