In [1]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([40.000,418.000,200.880]) # X:40.000 Y:418.000 Z:200.880
pl=np.array([497.000,423.00,210.880]) # X:497.000 Y:423.000 Z:210.880
pt=np.array([273.000,422.000,435.880]) # X:273.000 Y:422.000 Z:435.880

pcxz=(pr+pl)/2

print(pcxz)

hi
[268.5  420.5  205.88]


In [6]:
pz = pt - pcxz
print(pz)
px = pr-pl
print(px)
py = np.cross(px,pz)
py
p_x = pr-pcxz
print(p_x)
p_z = pt-pcxz
print(p_z)
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*(240+9) + p_y*probe_distance_from_tip
2.05
print(centerpoint)

[  4.5   1.5 230. ]
[-457.   -5.  -10.]
[-228.5   -2.5   -5. ]
[  4.5   1.5 230. ]
[ 0.01341041 -0.99987561  0.00830213]
[271.86668288 169.48122809 207.96424896]
