In [2]:
print("hi")
import numpy as np
# magnet facing upwards

pr = np.array([2.0, 417.0, 270.0])
pl = np.array([462.0, 415.0, 280.0])
pt = np.array([235.0, 416.0, 505.0])


pcxz=(pr+pl)/2

print(pcxz)

hi
[232. 416. 275.]


In [4]:
pz = pt - pcxz
print(pz)
px = pr-pl
print(px)
py = np.cross(px,pz)
py
p_x = pr-pcxz
print(p_x)
p_z = pt-pcxz
print(p_z)
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*(240+9) + p_y*probe_distance_from_tip

print(centerpoint)

[  3.   0. 230.]
[-460.    2.  -10.]
[-230.    1.   -5.]
[  3.   0. 230.]
[-0.00216412 -0.9999941   0.00266718]
[231.45669778 164.95148086 275.66959616]


In [ ]:
step = 10
radius = 95
npts = 4/3*np.pi*(radius/step)**3
t = npts #s
print(t)
print(t/60)
print(t/60/60)


In [ ]:
radius = 85
resol = 10
nperrad = int(radius/resol)+1
print(nperrad)
print(radius/nperrad)