In [11]:
print("hi")
import numpy as np
# magnet facing cosi
pr=np.array([2.000, 381.500, 129.000 ]) # X:2.000 Y:381.500 Z:129.000 
pl=np.array([490.000, 369.500, 137.500]) # X:490.000 Y:369.500 Z:137.500
pt=np.array([248.500, 379.000, 376.000]) # X:248.500 Y:379.000 Z:376.000

pcxz=(pr+pl)/2

print(pcxz)

hi
[246.   375.5  133.25]


In [13]:
pz = pt - pcxz
print(pz)

[  2.5    3.5  242.75]


In [15]:
px = pr-pl
print(px)

[-488.    12.    -8.5]


In [17]:
py = np.cross(px,pz)

In [19]:
py

array([  2942.75, 118440.75,  -1738.  ])

In [21]:
p_x = pr-pcxz
print(p_x)

[-244.      6.     -4.25]


In [23]:
p_z = pt-pcxz
print(p_z)

[  2.5    3.5  242.75]


In [25]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[-0.02283236 -0.99961376  0.01584317]


In [27]:
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*220 + p_y*probe_distance_from_tip

print(centerpoint)

[240.93007422 153.53576368 136.76797483]


In [ ]:
import numpy as np

center = np.array([100,100,100])
radius = 50
npoints = 5

x = np.linspace(center[0]-radius, center[0]+radius, 2*npoints)
y = np.linspace(center[1]-radius, center[1]+radius, 2*npoints)
z = np.linspace(center[2]-radius, center[2]+radius, 2*npoints)

xx, yy, zz = np.meshgrid(x,y,z)

res = (xx-center[0])**2+(yy-center[1])**2+(zz-center[2])**2<=radius**2
#print(np.shape(res))
#print(res)

it = np.nditer(res, flags=['f_index'])
for entry in it:
    if entry:
        pass
        #print(it.index)

for iz in range(len(z)):
    for iy in range(len(y)):
        for ix in range(len(x)):
            if res[ix,iy,iz]:
                print(f"{x[ix]}, {y[iy]}, {z[iz]}")