In [23]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([54.000,447,206.00]) # X:54.000 Y:453.000 Z:206.000 add 6 to y
pl=np.array([413.000,447.000,211.000]) # X:413.000 Y:453.000 Z:211.000 add 6 to y
pt=np.array([239.000,447.000,378.000]) # X:239.000 Y:453.000 Z:383.000 add 5 to y

pcxz=(pr+pl)/2
pcxz = [233.5, 447.0,  204.2]

print(pcxz)

hi
[233.5, 447.0, 204.2]


In [24]:
pz = pt - pcxz
print(pz)
px = pr-pl
print(px)
py = np.cross(px,pz)
py
p_x = pr-pcxz
print(p_x)
p_z = pt-pcxz
print(p_z)
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*(212) + p_y*probe_distance_from_tip
2.05
print(centerpoint)

[  5.5   0.  173.8]
[-359.    0.   -5.]
[-179.5    0.     1.8]
[  5.5   0.  173.8]
[ 0.00377097 -0.99998745  0.00329778]
[234.30717523 232.95268587 204.90588943]
