In [1]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([49.000,422.000,200.880]) # 49.000 Y:422.000 Z:200.880
pl=np.array([497.000,423.00,210.880]) # X:497.000 Y:423.000 Z:210.000
pt=np.array([279.000,422.000,435.880]) # X:279.000 Y:422.000 Z:435.880

pcxz=(pr+pl)/2

print(pcxz)

hi
[273.   422.5  205.88]


In [2]:
pz = pt - pcxz
print(pz)
px = pr-pl
print(px)
py = np.cross(px,pz)
py
p_x = pr-pcxz
print(p_x)
p_z = pt-pcxz
print(p_z)
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*(240+9) + p_y*probe_distance_from_tip
2.05
print(centerpoint)

[  6.   -0.5 230. ]
[-448.   -1.  -10.]
[-224.    -0.5   -5. ]
[  6.   -0.5 230. ]
[ 4.95325797e-03 -9.99987705e-01 -2.35182248e-04]
[274.24351541 171.45308669 205.8209575 ]
