In [1]:
print("hi")
import numpy as np
# magnet facing upwards
pr=np.array([23,373,265]) # X:23.000 Y:373.000 Z:265.000
pl=np.array([483,367,275]) # X:483.000 Y:367.000 Z:275.000
pt=np.array([256,371,498]) # X:256.000 Y:371.000 Z:498.000

pcxz=(pr+pl)/2

print(pcxz)

hi
[253. 370. 270.]


In [2]:
pz = pt - pcxz
print(pz)

[  3.   1. 228.]


In [3]:
px = pr-pl
print(px)

[-460    6  -10]


In [4]:
py = np.cross(px,pz)

In [5]:
py

array([  1378., 104850.,   -478.])

In [6]:
p_x = pr-pcxz
print(p_x)

[-230.    3.   -5.]


In [7]:
p_z = pt-pcxz
print(p_z)

[  3.   1. 228.]


In [8]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[-0.01076671 -0.99991641  0.00715867]


In [9]:
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*254 + p_y*probe_distance_from_tip
2.05
print(centerpoint)

[250.24318365 113.97140265 271.83297656]


In [ ]:
import numpy as np

center = np.array([100,100,100])
radius = 50
npoints = 5

x = np.linspace(center[0]-radius, center[0]+radius, 2*npoints)
y = np.linspace(center[1]-radius, center[1]+radius, 2*npoints)
z = np.linspace(center[2]-radius, center[2]+radius, 2*npoints)

xx, yy, zz = np.meshgrid(x,y,z)

res = (xx-center[0])**2+(yy-center[1])**2+(zz-center[2])**2<=radius**2
#print(np.shape(res))
#print(res)

it = np.nditer(res, flags=['f_index'])
for entry in it:
    if entry:
        pass
        #print(it.index)

for iz in range(len(z)):
    for iy in range(len(y)):
        for ix in range(len(x)):
            if res[ix,iy,iz]:
                print(f"{x[ix]}, {y[iy]}, {z[iz]}")