In [2]:
print("hi")
import numpy as np
# magnet facing cosi
pr=np.array([5,436,314]) # 5,436,308
pl=np.array([493,437,303]) # 490,428,300
pt=np.array([250,441,549]) # 248,438,544

pcxz=(pr+pl)/2

print(pcxz)

hi
[249.  436.5 308.5]


In [3]:
pz = pt - pcxz
print(pz)

[  1.    4.5 240.5]


In [4]:
px = pr-pl
print(px)

[-488   -1   11]


In [6]:
py = np.cross(px,pz)

In [7]:
py

array([  -290., 117375.,  -2195.])

In [8]:
p_x = pr-pcxz
print(p_x)

[-244.    -0.5    5.5]


In [9]:
p_z = pt-pcxz
print(p_z)

[  1.    4.5 240.5]


In [10]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[ 0.00460816 -0.9997603   0.02140356]


In [11]:
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*220 + p_y*probe_distance_from_tip

print(centerpoint)

[250.02324094 214.50322592 313.25265994]


In [24]:
fname = r'C:\cosi-measure\Software\COSI2\data\240708\Hamburg_ball_R130mm_d10mm.path'
file = open(fname)
lines = file.readlines()
xs  = []
ys  = []
zs  = []

for line in lines:
    xstr = line.split(' ')[0]
    ystr = line.split(' ')[1]
    zstr = line.split(' ')[2]
    x = float(xstr[1:])
    y = float(ystr[1:])
    z = float(zstr[1:])
    xs.append(x)
    ys.append(y)
    zs.append(z)
    
print('min x',min(xs))
print('max x',max(xs))
print('min y',min(ys))
print('max y',max(ys))
print('min z',min(zs))
print('max z',max(zs))

min x 124.0
max x 364.0
min y 90.0
max y 330.0
min z 190.0
max z 430.0
