In [1]:
print("hi")
import numpy as np
# magnet facing cosi
pr=np.array([7.000, 367.000,175.000]) # X:7.000 Y:369.000 Z:175.000 E:0.000
pl=np.array([495.000, 351.000,187.000]) # X:495.000 Y:353.000 Z:187.000 E:0.000
pt=np.array([255.000, 361.000,424.000]) # X:255.000 Y:363.000 Z:424.000 E:0.000

pcxz=(pr+pl)/2

print(pcxz)

hi
[251. 359. 181.]


In [2]:
pz = pt - pcxz
print(pz)

[  4.   2. 243.]


In [3]:
px = pr-pl
print(px)

[-488.   16.  -12.]


In [4]:
py = np.cross(px,pz)

In [5]:
py

array([  3912., 118536.,  -1040.])

In [6]:
p_x = pr-pcxz
print(p_x)

[-244.    8.   -6.]


In [7]:
p_z = pt-pcxz
print(p_z)

[  4.   2. 243.]


In [8]:
p_y_big = np.cross(p_z,px)+pcxz
p_y = p_y_big/np.linalg.norm(p_y_big)
print(p_y)

[-0.03096245 -0.9994672   0.01032645]


In [11]:
probe_distance_from_tip = 2.05
centerpoint = pcxz+p_y*220 + p_y*probe_distance_from_tip

print(centerpoint)

[244.12478802 137.06830745 183.2929893 ]


In [10]:
import numpy as np

center = np.array([100,100,100])
radius = 50
npoints = 5

x = np.linspace(center[0]-radius, center[0]+radius, 2*npoints)
y = np.linspace(center[1]-radius, center[1]+radius, 2*npoints)
z = np.linspace(center[2]-radius, center[2]+radius, 2*npoints)

xx, yy, zz = np.meshgrid(x,y,z)

res = (xx-center[0])**2+(yy-center[1])**2+(zz-center[2])**2<=radius**2
#print(np.shape(res))
#print(res)

it = np.nditer(res, flags=['f_index'])
for entry in it:
    if entry:
        pass
        #print(it.index)

for iz in range(len(z)):
    for iy in range(len(y)):
        for ix in range(len(x)):
            if res[ix,iy,iz]:
                print(f"{x[ix]}, {y[iy]}, {z[iz]}")

94.44444444444444, 72.22222222222223, 61.111111111111114
105.55555555555556, 72.22222222222223, 61.111111111111114
83.33333333333333, 83.33333333333333, 61.111111111111114
94.44444444444444, 83.33333333333333, 61.111111111111114
105.55555555555556, 83.33333333333333, 61.111111111111114
116.66666666666666, 83.33333333333333, 61.111111111111114
72.22222222222223, 94.44444444444444, 61.111111111111114
83.33333333333333, 94.44444444444444, 61.111111111111114
94.44444444444444, 94.44444444444444, 61.111111111111114
105.55555555555556, 94.44444444444444, 61.111111111111114
116.66666666666666, 94.44444444444444, 61.111111111111114
127.77777777777777, 94.44444444444444, 61.111111111111114
72.22222222222223, 105.55555555555556, 61.111111111111114
83.33333333333333, 105.55555555555556, 61.111111111111114
94.44444444444444, 105.55555555555556, 61.111111111111114
105.55555555555556, 105.55555555555556, 61.111111111111114
116.66666666666666, 105.55555555555556, 61.111111111111114
127.77777777777777